---
version: "3"
services:
  herro:
    build: .
    image: "registry.invoice2go.io/i2g/app:node10.19-kcl1.13"
    volumes:
      - "./:/code"
    command: ["true"]
    environment:
      - "NODE_ENV=test"

#    depends_on:
#      - "dynamodb"
#      - "kinesis"
#      - "minio"
#      - "postgres"
#      - "pushgateway"
#      - "redis"
#      - "xray"
#  dynamodb:
#    image: "registry.invoice2go.io/i2g/dynamodb-local:latest"
#    command: ["-sharedDb"]
#  kinesis:
#    image: "registry.invoice2go.io/i2g/kinesalite:latest"
#  minio:
#    image: "docker.invoice2go.io/minio:latest"
#    environment:
#      - "MINIO_ACCESS_KEY=itg-test"
#      - "MINIO_SECRET_KEY=itg-test"
#  redis:
#    image: "redis:3.2-alpine"
#  postgres:
#    image: "postgres:latest"
#    environment:
#      - "POSTGRES_USER=itg"
#      - "POSTGRES_PASSWORD=invoice2go"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready --username=postgres"]
#      interval: 100ms
#      retries: 50
#      timeout: 10s
#  pushgateway:
#    image: "docker.io/prom/pushgateway:v0.9.1"
#  xray:
#    image: "amazon/aws-xray-daemon:3.2.0"
#    environment:
#      - AWS_REGION=us-west-1
#    ports:
#      - "2000:2000/udp"
