on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: test
        run: echo "test"
