name: Octo Organization CI

on:
  - push
jobs:
  build:
    runs-on: int
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: echo Hello from Octo Organization
